---

- name: Install Nginx on all hosts
  hosts: smartway-servers
  tasks:
    - name: Add epel-repo on CentOS
      yum:
        name: epel-release
        state: present
      when: 
        - ansible_distribution == "CentOS"

    - name: Install Nginx on CentOS
      yum:
        name: nginx
        state: present
      when: 
        - ansible_distribution == "CentOS"

    - name: Install Nginx on Ubuntu
      apt:
        name: nginx
        state: latest
      when: 
        - ansible_distribution == "Ubuntu"

    - name: add index.html file
      template:
        src: ./index.html
        dest: /usr/share/nginx/html/index.html
      
    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

...
